#
# This file will be autogenerated by Chef. The node IPs are different
# in each environment (dev, ci, master, staging, prod). In development,
# use the environment variable LOG_REDIS_NODE to override. 
# 
# DO NOT MAKE ANY CHANGES TO THIS FILE.
#

# The following gives you the Redis node in the Master environment
# NB: Hardcoding the Redis node IP in this way is not ideal.
LOG_REDIS_NODE = ENV['LOG_REDIS_NODE'] || "10.254.1.204"
